# .github/workflows/build.yml

name: Build ZMK firmware

on:
  push:
    paths:
      - 'config/**'
      - 'build.yaml'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
